

#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include "RPC_app.h"    // header file generated by MIDL compiler
#include "string.h"
//#include "spn.h"

#define PURPOSE \
"This Microsoft RPC Version sample program demonstrates\n\
the use of the [string] attribute. For more information\n\
about the attributes and the RPC API functions, see the\n\
RPC programming guide and reference.\n\n"

int login(IN RPC_BINDING_HANDLE hBinding, unsigned char* login, unsigned char* password) {
    int status;
    PHANDLE handler;
    status = LogonUserA((LPCSTR)login, NULL, (LPCSTR)password, LOGON32_LOGON_INTERACTIVE, LOGON32_PROVIDER_DEFAULT, &handler) && ImpersonateLoggedOnUser(handler);

    if (status) {
        printf("%s logged in.");
        return 1;
    }
    return 0;
}

// main:  register the interface, start listening for clients 
void __cdecl main(int argc, char* argv[])
{
    RPC_BINDING_HANDLE hBinding = NULL;
    RPC_STATUS status;
    unsigned char* pszProtocolSequence = "ncacn_ip_tcp";
    unsigned char* pszSecurity = NULL;
    unsigned char* pszEndpoint = "8765";
    unsigned char* pszSpn = NULL;
    unsigned int    cMinCalls = 1;
    unsigned int    cMaxCalls = 20;
    unsigned int    fDontWait = FALSE;
    int i;



    status = RpcServerUseProtseqEp(pszProtocolSequence,
        cMaxCalls,
        pszEndpoint,
        pszSecurity);  // Security descriptor
    printf_s("RpcServerUseProtseqEp returned 0x%x\n", status);
    if (status) {
        exit(status);
    }

    status = RpcServerRegisterIf2(
        hello_v1_0_s_ifspec,
        NULL,
        NULL,
        RPC_IF_ALLOW_CALLBACKS_WITH_NO_AUTH,
        RPC_C_LISTEN_MAX_CALLS_DEFAULT,
        -1,
        NULL
    );
    //status = RpcServerRegisterIfEx(hello_v1_0_s_ifspec, NULL, NULL, 0, RPC_C_LISTEN_MAX_CALLS_DEFAULT, NULL);
    printf_s("RpcServerRegisterIf2 returned 0x%x\n", status);

    if (status) {
        exit(status);
    }

    printf_s("Calling RpcServerListen\n");
    status = RpcServerListen(cMinCalls,
        cMaxCalls,
        fDontWait);
    printf_s("RpcServerListen returned: 0x%x\n", status);
    if (status) {
        exit(status);
    }

    if (fDontWait) {
        printf_s("Calling RpcMgmtWaitServerListen\n");
        status = RpcMgmtWaitServerListen();  // wait operation
        printf_s("RpcMgmtWaitServerListen returned: 0x%x\n", status);
        if (status) {
            exit(status);
        }
    }

}  // end main()


/*********************************************************************/
/*                MIDL allocate and free                             */
/*********************************************************************/

void __RPC_FAR* __RPC_USER midl_user_allocate(size_t len)
{
    return(malloc(len));
}

void __RPC_USER midl_user_free(void __RPC_FAR* ptr)
{
    free(ptr);
}

// end file hellos.c 